remote_theme: rundocs/jekyll-Merlot-theme
author: Masanori Kobayashi & Takayuki Osugi
scss: |
  @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Noto+Serif+JP:wght@400;500;700&display=swap');
  .text-uppercase{
    text-transform: none !important; 
  }
  .markdown-body{
    font-family: 'Noto Sans JP', serif !important;
    line-height:1.7;
    font-weight: 500;
  }
  .markdown-body h1, .markdown-body h2, .markdown-body h3, .markdown-body h4, .markdown-body h5, .markdown-body h6, .markdown-body dt {
    font-family: 'Noto Sans JP', sans-serif !important;
  }
  .markdown-body img{
    border: solid 1px #aaa
  }
readme_index:
  with_frontmatter: true
theme: jekyll-theme-cayman